dims: 
  dim_company:
    - COMPANY_SK       # -> PK: DW 내에서만 의미 있는 고유 ID 역할
    - COMPANY_ID       # 자연키 (추가됨)
    - FNDT_DT          # -> Date
    - LISTD_DT         # -> Date
    - LISTD_ABOL_DT    # -> Date
    - SIC_CD_3
    - CT_CNTY_GU_CD
    - WG_GB
    - AS1C10132
    - ASCD10103
    - AS1C20102
  

  dim_time:
    - TIME_SK       # -> PK
    - BS_DT         # -> Date

  dim_industry:
    - INDUSTRY_SK      # -> PK
    - INDUSTRY_CODE    # -> 업종 코드 (A01, C10 등)
    - INDUSTRY_NAME    # -> 업종 한글명


facts: # - Company_SK, Time_SK 키로 연결
  fact_financial_statement: # 재무제표
    - FN1_1
    - FN1_2
    - FN1_3
    - FN1_4
    - FN1_5
    - FN1_6
    - FN1_7
    - FN1_8
    - FN1_9
    - FN1_10
    - FN1_11
    - FN1_11_1
    - FN1_11_2
    - FN1_11_3
    - FN1_11_4
    - FN1_13
    - FN1_13_1
    - FN1_14
    - FN1_15
    - FN1_16
    - FN1_17
    - FN1_18
    - FN1_19
    - FN1_20
    - FN1_21
    - FN1_21_1
    - FN1_22
    - FN1_22_1
    - FN1_22_2
    - FN1_23
    - FN1_24
    - FN1_24_1
    - FN2_1
    - FN2_1_1
    - FN2_2
    - FN2_2_1
    - FN2_3
    - FN2_3_1
    - FN2_3_2
    - FN2_3_3
    - FN2_3_4
    - FN2_3_5
    - FN2_4
    - FN2_5
    - FN2_5_1
    - FN2_7
    - FN2_8
    - FN2_9
    - FN2_10
    - FN2_10_1
    - FN3_1
    - FN3_2
    - FN3_2_1
    - FN3_2_2
    - FN3_4_1
    - FN3_4_2
    - FN3_7
    - FN3_8
    - FN3_10_1
    - FN3_11
    - FN3_11_1

  fact_financial_ratios: # 재무비율
    - FN3_3
    - FN3_4
    - FN3_5
    - FN3_6
    - FN3_10
    - R001
    - R006
    - R007
    - R008
    - R012
    - R002
    - R015
    - R016
    - R013
    - R014
    - R018
    - R019
    - R020
    - R021
    - R022
    - R023
    - R024
    - R025
    - N001
    - R009
    - N002
    - N003
    - N012
    - N004
    - N005
    - N006
    - R003
    - R004
    - N007
    - N008
    - N009
    - N010
    - N011

  fact_credit_behavior: #신용
    - DA0D00021
    - DA0D00024
    - DA0D00025
    - DA0D00026
    - DA0D00026_1
    - DA0D00027
    - DA0D00028
    - DA0D00029
    - DA0D00029_1
    - DA0D00030
    - DA0D00031
    - DA0D00032
    - DA0D00032_3
    - DB0D00005
    - DB0D00006
    - DB0D00007
    - DB0D00008
    - DA0D00042
    - DB0D00009
    - DB0D00010
    - DB0D00011
    - DB0D00012
    - DA0D00044_1
    - DA0D00044_2
    - DA0D00044_3
    - DA0D00044_4
    - DA0D00033_1
    - DA0D00034_1
    - DA0D00035_1
    - DA0D00035_3_1
    - DA0D00035_4_1
    - DA0D00033_2
    - DA0D00034_2
    - DA0D00035_2
    - DA0D00035_3_2
    - DA0D00035_4_2
    - D2011000H
    - D2B000001
    - D2B000005
    - D2B000012
    - D2B000012_1
    - D2B000012_2
    - D2B000012_3
    - D2B000002
    - D2B000003 
    - CORP_GRAD

  # fact_modeling_target: 
  #   - CORP_GRAD
  #   - PERF_12M